looker-open-source/actions

src/hub/action_request.ts
src/hub/index.ts

And adds a couple small things like fetching `ran_at`

Improve error handling in streaming JSON functions

---

src/actions/amazon/test_amazon_s3.ts
src/actions/google/google_cloud_storage.ts
src/actions/google/test_google_cloud_storage.ts

not sure why save doesn't work but it doesn't. this does work.

GCS move from save to WriteStream

---

src/actions/slack/slack.ts
src/actions/slack/test_slack.ts

Fixes connection issues with slack by changing options to properly match method parameters

Fixed our slack stuff

---

src/server/server.ts

See individual commits for details.

Several fixes for the Raven error handling

---

src/server/server.ts

Memoize the action list JSON since it never changes at runtime

---

src/actions/airtable/airtable.ts
src/actions/amazon/amazon_s3.ts
src/actions/azure/azure_storage.ts
src/actions/debug/debug.ts
src/actions/google/google_cloud_storage.ts
src/actions/hipchat/hipchat.ts
src/actions/jira/jira.ts
src/actions/marketo/marketo.ts
src/actions/segment/segment.ts
src/actions/segment/test_segment.ts
src/actions/segment/test_segment_group.ts
src/actions/sendgrid/sendgrid.ts
src/actions/sftp/sftp.ts
src/actions/slack/slack.ts
src/actions/twilio/twilio.ts
src/actions/twilio/twilio_message.ts
src/hub/action.ts
src/hub/action_request.ts
src/hub/action_response.ts
src/hub/sources.ts
src/server/server.ts
tslint.json

Adds a new linter rule, strict-boolean-expressions, to catch these issues.

Fix errors where expressions were always truthy

---

src/actions/segment/segment.ts
src/actions/segment/test_segment.ts

This reverts commit 1b41e2326524c5b73def1aaf33f8920de8ba68e9.

Revert "Disable segment streaming temporarily (#170)"

---

src/actions/marketo/marketo.ts
src/actions/marketo/test_marketo.ts

Marketo fix

---

package.json

Adds a command ` yarn debug ` that will allow the Chrome debugger to be attached

Added debug command to package.json

---

package.json
yarn.lock

Revert "Update to TypeScript 3.0.1"

---

src/actions/google/test_google_cloud_storage.ts

#193 and #194 combine to break each other

Resolve a merge conflict causing the tests to fail

---

src/actions/jira/jira.ts
src/actions/jira/test_jira.ts

Catch SDK/auth errors and forward them to the user.

Improve Jira errors when fetching form

---

src/hub/action_request.ts
src/xpc/execute_process_queue.ts

Also switches to use Winston's info hash which formats additional metadata in a standard way and allows pluggable log formats.

Log streaming errors more verbosely

---

src/hub/action_request.ts
src/server/server.ts

See individual commits for details.

Several improvements to streaming logging and error handling

---

src/actions/slack/slack.ts
src/actions/slack/test_slack.ts

cc/ @phillipperalez @wilg 
might be a cleaner way but i think this works. would love 👀

Add support for pagination

---

src/actions/slack/README.md

Just had a customer wonder why they couldn't see any public channels, and this was why

Added note for bot invitation

---

src/actions/dropbox/dropbox.ts
src/actions/dropbox/test_dropbox.ts

Addressing some internal feedback for the messaging

Changed the wording of Dropbox log label and added a description

---

src/actions/dropbox/dropbox.ts
src/actions/dropbox/test_dropbox.ts

Changed wording for Dropbox action

Dropbox UI Cleanup

---

docs/action_api.md
src/hub/oauth_action.ts

Work in progress update of all docs on ActionHub

Let's Update the Action Hub API Docs

---

src/actions/dropbox/dropbox.ts
src/actions/dropbox/test_dropbox.ts

Addresses some feedback from product management

Dropbox folder name

---

tsconfig.npm.json

Fixes https://github.com/looker/custom-action-hub-example which currently is running into 
```
Error: Cannot find module '../crypto/aes_transit_crypto'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
at Function.Module._load (internal/modules/cjs/loader.js:507:25)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:20:18)
at Object.<anonymous> (/Users/Looker/Source/custom-action-hub-example/node_modules/looker-action-hub/lib/hub/index.js:14:30)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
at Function.Module._load …
```

Add src/crypto into tsconfig.npm

---

src/actions/dropbox/dropbox.ts

Based on internal feedback from product we are slightly changing the wording of Dropbox

Reworded Dropbox description

---

src/actions/slack/slack.ts

Increase api limit to minimize api calls to avoid api rate limiting

---

src/actions/slack/README.md

take out anchor for URL in README

---

src/actions/marketo/README.md
src/actions/marketo/marketo.ts
src/actions/marketo/marketo_transaction.ts
src/actions/marketo/test_marketo.ts

Reverts looker/actions#243
For testing branch

Revert "Fabio looker/marketo endpoint enhancements"

---

src/actions/queueaction/test_queue_action.ts
src/hub/action.ts
src/server/server.ts
src/xpc/extended_process_queue.ts
yarn.lock

Creating a separate process queue for those actions that may take a very long time - I intend to have these not block just heavy actions that perform heavier but faster work

Extended process queues

---

src/actions/slack/legacy_slack/slack.ts
src/hub/sources.ts
src/xpc/extended_execute_process.ts
src/xpc/extended_process_queue.ts

Improves the extended process queue. This allows a action process to exist longer than its connection to Looker. This frees up the other process queues from being held up by very long actions that may just be ensuring jobs are getting done even after the data is uploaded

Improved extended execute

---

src/actions/mparticle/mparticle_constants.ts
src/actions/mparticle/mparticle_transaction.ts

By request, changing this default event_name to be slightly different
Also adds a default for custom_event_type in the same vein

One additional rule surrounding custom_event_type

---

src/actions/slack/test_slack.ts
src/actions/slack/test_utils.ts
src/actions/slack/utils.ts
src/hub/action_request.ts

Fixes cases where empty payloads from send if no results schedules hung the action request streamer

Empty Stream Payload Fix

---

package.json
yarn.lock

using https://github.com/request/request/commit/392db7d127536ff296fb06492db9430790a32d6c
to mitigate prototype pollution

All versions of the request library are now using a patched version

---

src/actions/slack/slack.ts
src/actions/slack/slack_client_manager.ts
src/actions/slack/test_slack.ts
src/actions/slack/test_slack_client_manager.ts
src/hub/action_form.ts

`/oauthCheck`, `/test`, `/form`, `/execute`

Multiple workspace support for slack

---

src/actions/google/drive/sheets/google_sheets.ts

Solves race condition of data rows coming in before sheet size could update

Google Sheets - await mutex operations

---

src/actions/google/drive/google_drive.ts
src/actions/google/drive/sheets/test_google_sheets.ts
src/actions/google/drive/test_google_drive.ts

Adds proper corpus values to Google Drive/Sheets and the ability to select what Drive to send the data.
Also adds ability to select top level Drive Root as selectable folder

Add support for Shared Drives for Google Sheets/Drive

---

src/actions/google/drive/google_drive.ts
src/actions/google/drive/sheets/google_sheets.ts

Adds ability to upload data to Shared Drives correctly

Add parameters for Shared Drive uploads

---

src/actions/google/gcs/google_cloud_storage.ts

Adds correct path for GCS icon to load

Adding icon back for gcs

---

src/actions/google/drive/sheets/google_sheets.ts

By checking and updating the max_row_count first we prevent partial uploads
Make sure that resolve is called for every success case

Google Sheets Bugfixes

---

src/actions/google/drive/sheets/google_sheets.ts

Resize will now ALWAYS be checked in before a large batch update of rows. In addition this reduces the number of blocks that use Miutex protected scopes

Refactor Sheets Resize to Flush scope

---

package.json
yarn.lock

Updating mocha version to address potential security defect

Updated mocha

---

src/hub/action_request.ts
test/test_action_request.ts

Address case where users input the file extension along with the file name

Handle user input of file extension

---

src/actions/sagemaker/sagemaker_train_linearlearner.ts
src/actions/sagemaker/sagemaker_train_xgboost.ts

Title is pretty self explanatory. Changed "traingin" to "training"

Fixed SageMaker description typos

---

src/actions/google/drive/sheets/google_sheets.ts
src/actions/google/drive/sheets/test_google_sheets.ts

Addresses an issue where the wrong sheet is cleared out when the first sheet is hidden

Change clear sheet function

---

src/actions/twilio/twilio_message.ts

Changing confusing field labels

Fix twilio phone number typo

---

src/actions/google/drive/sheets/google_sheets.ts

This will prevent race conditions with resizing the Google Sheet

GoogleSheets CSVParsing async -> sync data event handling

---

src/actions/google/drive/google_drive.ts
src/actions/google/drive/sheets/test_google_sheets.ts
src/actions/google/drive/test_google_drive.ts

Include mimetype in file metadata sent to google drive

Add mimetypes for google drive files

---

src/actions/google/drive/sheets/google_sheets.ts

Global catch will prevent uncaught exceptions from bubbling up and hanging multiprocess executions

Global catch to prevent issues with hanging actions

---

src/actions/dropbox/dropbox.ts
src/actions/dropbox/test_dropbox.ts

Added for when users want multiple versions of the same file in Dropbox

Add optional timestamp to dropbox filename

---

Dockerfile

Will fix creating a new Docker container on Node 14.8

Yarn already committed and referenced in .yarnrc

---

lib/actions/firebase/firebase.d.ts
lib/actions/firebase/firebase.js
lib/actions/index.d.ts
lib/actions/index.js
lib/actions/slack/utils.js
src/actions/firebase/firebase.ts

Updated Firebase lib/ references via `yarn build`
Remove double add of Firebase

fix: Add Firebase lib/ references

---

lib/actions/firebase/firebase.d.ts
lib/actions/firebase/firebase.js
src/actions/firebase/firebase.ts
src/actions/firebase/test_firebase.ts

2 changes in this PR
- adding extra logs in fire base action so that in case of issue debugging can be easy and developers can see how action is working when actually deployed
- minor update in variable name to reflect changes being made in looker code base

add logs to fire base action and some minor variable name change

---

lib/actions/firebase/firebase.js
src/actions/firebase/firebase.ts

update firebase action to include body in the notification

update firebase action to include body in the notification

---

package.json
src/actions/marketo/test_marketo.ts
src/actions/mparticle/test_mparticle.ts
src/actions/segment/test_segment.ts
test/test.ts
yarn.lock

Resolve formidable dependencies to use version 3.2.4

Upgrade formidable

---

src/actions/google/ads/customer_match.ts
src/actions/google/ads/lib/ads_form_builder.ts

Fixing bug on Google Ads Customer Match to ignore draft ads accounts

fix: customer match - ignore errors on sub accounts

---

cloudbuild_container.yaml
package.json

Adding a cloudbuild configuration to be able to build a container for GCP CloudRun

Add cloudbuild_container file to build a container in CloudBuild

---

lib/actions/google/drive/google_drive.js
lib/actions/google/drive/sheets/google_sheets.js
src/actions/google/drive/google_drive.ts
src/actions/google/drive/sheets/google_sheets.ts

Adds further logging to catch error events and attempt to correctly send those errors back to the user.

Add more logging and messaging for Google Sheets and Google Drive

---

lib/actions/slack/utils.js
src/actions/slack/utils.ts

Adds title field for Slack finalize upload calls.

Add title to finalize upload

---

lib/actions/dropbox/dropbox.js
lib/api_types/data_webhook_payload_scheduled_plan.d.ts
lib/hub/action_request.d.ts
lib/hub/action_request.js
src/api_types/data_webhook_payload_scheduled_plan.ts
src/hub/action_request.ts

This allows us to use the callback url in the edge server.

adds asyncCallbackUrl to actionScheduledPlan object.

---

src/actions/google/drive/google_drive.ts
src/actions/google/drive/sheets/google_sheets.ts

Add winston logs where needed for oauth flow

Add winston logs where needed for oauth flow

---

package.json

Bump version for Airtable changes

---

src/actions/airtable/airtable.ts

This change will add more error logging to the airtable refresh failure.

Add error logging to airtable refresh failure

---

lib/hub/action_response.d.ts
lib/hub/action_response.js
src/hub/action_response.ts
test/test_action_response.ts

We have a project to improve error visibility for customers. This implements the new error_detail interface we are adding to the Action Response message that will then be consumed in helltool.

Adds error detail interface to ActionResponse class.

---

lib/actions/google/drive/google_drive.d.ts
lib/actions/google/drive/google_drive.js
src/actions/google/drive/google_drive.ts
src/actions/google/drive/sheets/test_google_sheets.ts
src/actions/google/drive/test_google_drive.ts

There was an error with the whitespace and properly quoting the search value. Search now returns values. Refactored query construction to another method to help defend against regressions or thoughtless changes

Fixing sheets/drive forms for searching

---

src/actions/google/ads/customer_match.ts
src/actions/google/ads/lib/ads_request.ts

Adding Winston logs
Changelog: 
[ ] Add winston logs in ads_request.ts
[ ] Add logs in customer_match.ts using available function

refactor: Add error messaging winston logs

---

src/actions/google/gcs/google_cloud_storage.ts

Changelog:
[ ] Add error messaging to Google Cloud Storage action

refactor: Add error messaging winston logs to GCS

---

package.json

We actually need to update it to 1.4.6

updates tag to 1.4.6

---

lib/actions/slack/slack.js
lib/actions/slack/slack_client_manager.js
lib/actions/slack/utils.js
src/actions/slack/slack.ts
src/actions/slack/slack_client_manager.ts
src/actions/slack/utils.ts

Change Log:
[ ] Add Log prefix to match with other actions
[ ] Add Webhook ID to existing logs
[ } Add missing logs where necessary

Refactor: add Log prefix and webhookId, add missing logs

---

lib/actions/google/ads/lib/ads_request.js
src/actions/google/ads/lib/ads_request.ts

Change Log:
[ ] Add missing logs prefixes
[ ] Add `` to the argument passed to safeParseJson to make sure a string is passed

fix: add  in the argument of safeParseJson, add missing logs

---

lib/actions/google/drive/sheets/google_sheets.js
src/actions/google/drive/sheets/google_sheets.ts
src/actions/google/drive/sheets/test_google_sheets.ts

This change will add the details for the google_sheets action.
Mostly adding new tests to cover the error path.

Add error details for google_sheets action

---

lib/actions/google/drive/google_drive.d.ts
lib/actions/google/drive/google_drive.js
src/actions/google/drive/google_drive.ts
src/actions/google/drive/sheets/test_google_sheets.ts
src/actions/google/drive/test_google_drive.ts

Reverting all of the form search commits for Sheets and Drive to fix documentation for how the changes work

Revert form search mode

---

lib/actions/google/drive/sheets/google_sheets.d.ts
lib/actions/google/drive/sheets/google_sheets.js
src/actions/google/drive/sheets/google_sheets.ts

Increase retry logic coverage for Google Sheets

Retry Coverage for Google Sheets

---

lib/actions/google/drive/google_drive.js
src/actions/google/drive/google_drive.ts
src/actions/google/drive/sheets/google_sheets.ts

Forgot to ensure validation checks happen before proceeding with action execution
Use validation function everywhere

Update Google Action allowlist feature

---

lib/actions/google/drive/sheets/google_sheets.js
lib/hub/action_request.js
src/actions/google/drive/sheets/google_sheets.ts
src/hub/action_request.ts

Google Sheets formatting fixes
Also adding and extra event handler to check statusCode

Fixing Formatting and Error Handling for Callbacks

---

lib/actions/google/ads/lib/api_client.js
src/actions/google/ads/lib/api_client.ts

Chage Log:
[ ] Upgrading GAds version to v17

fix(chore): Upgrade GAds API version to v17

---

lib/actions/google/analytics/lib/csv_header_transform_stream.d.ts
lib/actions/google/drive/sheets/google_sheets.js
lib/crypto/local_crypto_testing.d.ts
lib/hub/action_request.d.ts
src/actions/google/drive/sheets/google_sheets.ts
src/actions/google/drive/sheets/test_google_sheets.ts

* We need to wait for retriableResize to complete before attempting to paste our new data.

Fix sheets resize race condition

---

lib/actions/google/drive/sheets/google_sheets.js
src/actions/google/drive/sheets/google_sheets.ts
src/actions/google/drive/sheets/test_google_sheets.ts
yarn.lock

This will allow Sheets to have a larger and easier to modify list of error codes we want to retry during execution

Add retriable error list

---

docs/deploying.md

Use Cloud Run build file for example of self hosted action hub.

Update deploy docs to use Cloud Run

---

lib/actions/google/drive/sheets/google_sheets.js
src/actions/google/drive/sheets/google_sheets.ts

Connection resets are ephemeral and should be retried

Add 409 as a retriable error case

---

lib/actions/firebase/firebase.js
src/actions/firebase/firebase.ts

Fixes bug with apns-expiration being a number and not a string

Stringify apns expiration

---

lib/actions/google/drive/sheets/google_sheets.js
src/actions/google/drive/sheets/google_sheets.ts
src/actions/google/drive/sheets/test_google_sheets.ts

Error codes properly committed back to Looker

Patch validation mesages

---

lib/actions/google/common/oauth_helper.js
src/actions/google/common/oauth_helper.ts

Trace oauth with webhookIds for easier debugging of network issues

New webhookId tracing for ads oauth

---

lib/actions/google/drive/sheets/google_sheets.js
src/actions/google/drive/sheets/google_sheets.ts

Use the readable event instead of data to guarantee no race conditions for uploading data to google sheets and resizing

Sync Streaming

---

lib/actions/google/ads/lib/api_client.js
src/actions/google/ads/lib/api_client.ts

Update membership lifetime to 540 days due to changes in ads API ([announcement](https://ads-developers.googleblog.com/2025/02/update-to-customer-match-membership.html#:~:text=Required%20actions%20for%20Google%20Ads,our%20Google%20Ads%20API%20forum.)).

Update lifetime to correct maximum

---

lib/xpc/execute_process.js
src/xpc/execute_process.ts

This also adds debug statements to see where the empty brakcets are being returned if they still are.

Adds even more checks to ensure no empty error message will be returned.

---

package.json

Updates package.json and adds 1.5.18 tag to master

Update package.json, tags HEAD 1.5.18
