looker-open-source/actions

- src/actions/segment/segment.ts
- src/actions/segment/test_segment.ts
- src/actions/segment/test_segment_group.ts
- src/actions/segment/test_segment_track.ts
This should fix segment. The oboe error handling was catching the error and removing the stack trace for an assertion error that timestamp was a Date type and not a numeric timestamp.
> Segment timestamp type to date

- src/actions/slack/slack.ts
this masked the bug from https://github.com/looker/actions/pull/154
> Import Slack so that type definitions come through

- src/actions/slack/slack.ts
The Slack SDK throws an error if `initial_comment` is set to `undefined`, but is fine with an empty string.
> Don't let initial_comment be undefined for Slack

- src/hub/action_request.ts
Currently, an error occurring during the web request to the `download_url` will throw an exception and terminate the process.
This change turns the `stream` function to return a promise that will be rejected upon a streaming failure and allowing that error to be propagated upwards.
> Handle errors during download_url web request

- src/actions/segment/segment.ts
- src/actions/segment/test_segment_track.ts
identify and group use trait but track uses properties per:
https://segment.com/docs/sources/server/http/#track
> move traits to properties for the segment track call

- src/actions/segment/segment.ts
`e` could be a string here potentially which would cause a blank error message
> try to capture better error info for segment

- src/actions/segment/segment.ts
- src/actions/segment/test_segment.ts
We are encountering memory issues with our streaming JSON parser (Oboe) and so disable Segment while we determine the best course of action.
> Disable segment streaming temporarily

- src/hub/action_response.ts
The response value was being ignored by Looker previously because the Action API nests these inside a "looker" key.
> ActionResponse properly sets the `looker` key

- src/actions/segment/segment.ts
- src/actions/segment/test_segment.ts
- src/hub/index.ts
LookmlModelExploreField is not the same as what Looker will actually send. The fields are right, but some are omitted in json_detail.
I introduced this in https://github.com/looker/actions/pull/172 – it's tricky when applying types to JSON because you can end up lying to yourself.
closes https://github.com/looker/helltool/issues/38148
> Fix the Hub.Field type to be partial

- src/actions/slack/slack.ts
- src/hub/action_form.ts
- src/server/server.ts
In general, passes the error messages back to Looker in a way it can understand them.
Specifically also catches then pretties up the error messages for a common Slack error message.
> Improve error handling for form errors

- .dockerignore
- Dockerfile
The order that operations are listed in the Dockerfile were not optimal with respect to maximizing the use of the build cache. It is best to copy the package.json (and related files) out into their own instruction and then install packages.
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#leverage-build-cache
> Make Dockerfile more cache-friendly

- src/hub/action.ts
- src/xpc/execute_process.ts
Adding an extra log message and redoing .catch to be immediately attached for execute_process to capture unhandled exceptions (small race condition)
> Child Process Error Handling Improvements

- tsconfig.npm.json
Ensures that users like myself who run private hubs can still pull from GitHub during development.
**Problem**
```
$ yarn start
yarn run v1.9.4
$ ./node_modules/.bin/ts-node ./src/index.ts
Error: Cannot find module '../xpc/execute_process_queue'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
at Function.Module._load (internal/modules/cjs/loader.js:507:25)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:20:18)
at Object.<anonymous> (C:\Users\<...>\node_modules\looker-action-hub\lib\server\server.js:19
:29)
```
**Solution**
Ensure XPC stuff gets compiled during postinstall.
> Include xpc in NPM tsconfig

- src/server/server.ts
We've determined AWS's [NAT Gateway](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html) is timing out action requests longer that 5 minutes in certain deployment setups. This attempts to prevent that by regularly sending newlines in the HTTP response body (since they don't affect JSON parsing).
This removes a workaround we had in place for older versions of Looker where the execute request would return 400 in the event of an error. Older versions of Looker (<5.14.25, 5.16.0 – 5.16.13, 5.18.0, 5.18.1) couldn't handle a 200 with a failure message – they just treated those as successes. Unfortunately due to the nature of this keep-alive we have to send the HTTP status code immediately before we know whether the action succeeded, meaning older Looker instances will not …
> Execute and form requests attempt to keep the connection alive

- package.json
- yarn.lock
from: https://github.com/dominictarr/event-stream/issues/115
Dependency libraries should have already updated this but let's make sure that the version is at a non-compromised version explicitly. This did not affect production as this is a ` nodemon ` vulnerability. We do not run nodemon for prod, only for test/dev commands.
> lock event-stream to non-compromised version 3.3.4 - Prod unaffected // Test/Dev Security Fix

- src/actions/azure/azure_storage.ts
- src/actions/azure/test_azure_storage.ts
The Container object returned from the Azure ` listContainersSegmented ` call actually doesn't have an `id` component. The correct way to identify a container is its name
> Slight refactor of Azure - Looking at container errors

- src/actions/webhook/webhook.ts
JsonDetailLiteStream can go above 5000 rows and actually be unlimited, and json:true should help with some cases of request-promise-native throwing a weird error when readable is null
> Update to JsonDetailLiteStream and use json:true to prevent errors

- src/actions/webhook/webhook.ts
Reverts looker/actions#267
Going to come back and look at this later, causing issues with Zapier that I did not catch in testing
> Revert "Update to JsonDetailLiteStream and use json:true to prevent errors"

- src/actions/marketo/README.md
- src/actions/marketo/marketo.ts
- src/actions/marketo/marketo_transaction.ts
- src/actions/marketo/test_marketo.ts
PR adds additional modes to the Marketo action, specifically:
- Being able to update leads WITHOUT providing a campaign ID
- Being able to update leads and add them to a list
- Being able to update leads and remove them from a list
> Fabio looker/marketo endpoint enhancements

- src/actions/mparticle/mparticle_constants.ts
- src/actions/mparticle/mparticle_transaction.ts
Turns out that the mParticle batch API endpoint requires `event_name` to be present, but the Looker user isn't obligated to provide one in the data - setting a sensible default to catch this edge case.
@phillipperalez
> Fix to add default event_name when not present in Looker data

- src/actions/mparticle/README.md
Missed a spot when copying over an existing readme, fixed typo
@phillipperalez
> Update typo in mParticle's README.md

- src/actions/mparticle/mparticle_constants.ts
- src/actions/mparticle/mparticle_transaction.ts
@phillipperalez could you please confirm if this env var was set on merge initially? I'm not sure the process for getting the variables set, but the client was running into issues when trying to send data > 100 of the batch size. This PR removes the need for the constant, because the API on mParticle's end is fixed and not subject to change. Thanks!
> Change process env constant to hardcoded in mParticle action

- src/hub/action_request.ts
- test/test.ts
- test/test_json_detail_stream.ts
We need to only care about the top level data key for onRow calls in json_detail formats
> Fix streaming pivot errors

- src/actions/azure/azure_storage.ts
Fixed a case where incorrectly formatted keys lead to key disclosure in actionhub logs
> Do not allow Azure to log access keys

- src/actions/sagemaker/sagemaker_train_linearlearner.ts
- src/actions/sagemaker/sagemaker_train_xgboost.ts
- src/actions/sagemaker/utils.ts
Added default regions for S3. If getBucketLocation(...) for AWS S3 returns a null LocationConstraint, the default is "us-east-1"
> Added default S3 region

- src/actions/slack/slack_client_manager.ts
- src/actions/slack/test_slack.ts
- src/actions/slack/test_slack_client_manager.ts
To allow existing schedules to work without the user has to go back to the scheduler modal to select the workspace.
> slack: fallback to first workspace

- src/actions/sendgrid/sendgrid.ts
- src/actions/sftp/sftp.ts
- src/hub/action_request.ts
- src/hub/utils.ts
- test/test_action_request.ts
This change proposes inferring the file extension for webhook payloads that don't have the `attachment` field (equivalent to streaming formats).
One use-case this solves is when customers attempt to send a query result as an Excel file to Slack. The Slack API is dependent on an `filename` field to determine file type, and absent this field, what gets posted is a file called `Untitled` that shows up as a `zip` instead of a `xlsx` file.
> Infer file extension for streaming formats

- src/actions/google/drive/sheets/google_sheets.ts
There is a race condition where return can be called before the streaming function is done.
> Sheets remove return call in flushing rows

- src/actions/google/drive/google_drive.ts
Drive/Sheet file list should have trashed: false in q param
> Fix to listing deleted folders in Drive/Sheet Forms

- src/hub/action.ts
Using this for more visibility into Execute Queue Usage. May rewrite to use p-queue 'active' events instead
> Add log when ExecuteProcess job is Enqueued

- src/actions/google/drive/sheets/google_sheets.ts
- src/actions/google/drive/sheets/test_google_sheets.ts
Before this change a record like `This tricky",string` would be sent incorrectly as `"This tricky",string"` which is invalid CSV. This PR reformat all `"` in strings to be correct `""` - making the example `This tricky"",string` and correct CSV
> Make sure quotes properly formatted for CSV lines

- src/actions/google/drive/sheets/google_sheets.ts
Lock request size before resizing sheet, reducing error rates that the batch update will mis-size the sheet
> Move resize logic until after request size is locked

- src/actions/auger/test_auger_train.ts
- src/actions/google/gcs/google_cloud_storage.ts
- src/actions/google/gcs/test_google_cloud_storage.ts
Add Overwrite form value to Google Cloud Storage. If there is a value and overwrite is set to "No" - the action will add a timestamp to the end of the filename
Fix Auger AI tests
> Fix Tests and Add Overwrite to GCS

- src/actions/segment/segment.ts
- src/actions/segment/test_segment_group.ts
Currently, if a dimension has a value of 0 it is mapped to a segment trait as an empty array []. This simple fix allows us to successfully pass a value of 0 to segment. Included is a test to ensure there are no regressions on this functionality.
> 🐛 [SEGMENT]: 0 dimension value bug fix

- src/actions/slack/legacy_slack/slack.ts
- src/actions/slack/slack.ts
- src/actions/slack/test_utils.ts
- src/actions/slack/utils.ts
This adds private channel support to the legacy slack action. Additionally, it enables private channel support to customer-hosted instances via the legacy slack action.
This undoes most of the changes in https://github.com/looker/actions/pull/279 which introduced this due to token confusion. `xoxp` vs `xoxb` token usage can be handled in documentation.
fixes: https://github.com/looker/actions/issues/227
> allow legacy slack action to post to private channels

- src/actions/slack/legacy_slack/README.md
Updated the Slack Attachment README with new bot user setup procedure and screenshots. Merge [this PR](https://github.com/looker/actions/pull/361) first.
> Slack Attachment bot user setup updates

- docs/action_api.md
The action_api.md document is outdated supported_download_settings does not accept a boolean anymore it should be an array of strings.
> Updated action_api.md to reflect changes for supported_download_settings

- src/hub/action_request.ts
We need to add the ability to send messages without payloads with no scheduled plan info.
> Allow scheduled plan and attachment to be null in empty() check

- src/actions/slack/test_utils.ts
- src/actions/slack/utils.ts
- src/hub/action_request.ts
- test/test.ts
- test/test_action_request.ts
Remove whitespace and add file extensions to custom filenames for slack actions
> Fix slack attachments on ios

- src/actions/marketo/README.md
Adding a note that the Marketo action is being deprecated, per convo with @DillonMorrison.
> adding deprecation note

- .gitignore
- .vscode/settings.json
Here's the story:
I added a `lib` folder to my action directory, but realized it wasn't being tracked by git. This is because the .gitignore had an entry for "lib".
But I couldn't see a root "lib" folder in my VS Code editor... Eventually I realized that the `.vscode/settings.json` file present in the repo was ignoring it. This file was originally added by Wil several years ago.
It makes sense that some people would want to change their editor settings, but those should be customized on a per-user basis, not made part of the repo itself.
So this commit deletes the `.vscode` folder and adds it to the gitignore for the future.
I've also modified the "lib" line to "/lib/" so it will only match on the root folder and not any subfolders or files.
I also slightly rearranged the entries and …
> Remove vscode settings and tweak gitignore

- docs/action_api.md
`csv_zip` option is available in `api_types/integration.ts`, but is not in documenation
> Add "csv_zip" in supported_formats, which is available from integration

- src/actions/google/drive/sheets/google_sheets.ts
Updates buffers to reduce API usage for batchUpdate Sheets API calls
Also trim whitespace for quoted fields to prevent csvparse from crashing
> Google Sheets Buffer Updates

- src/actions/hubspot/hubspot.ts
- src/actions/hubspot/test_hubspot_companies.ts
- src/actions/hubspot/test_hubspot_contacts.ts
We've been trying to use the Hubspot action to send some data from looker into Hubspot company properties. This is not working due to the fact that looker sends data in the form of `view.dimension`, for example: `customer.revenue` to Hubspot properties. However Hubspot properties do not support the use of dots `.` in their names.
This PR replaces those dots with underscores, which is the default behaviour when adding a dot in a property name in the Hubspot UI.
Tagging @luskin since you were the original author, thanks for creating this custom action!
> Replace dot with underscore in property names for Hubspot action

- src/actions/hubspot/README.md
it's confusing what field Hubspot expects to be tagged (many folks think its email, rather than an api-only field). Feel free to change this around - I've only tested out the contact_id part, but company_id seems to follow suit in the same way.
> Update Readme with Fields

- src/actions/google/drive/sheets/google_sheets.ts
Allow the google sheet batch size to be set by an environment variable. Otherwise defaults to 4096
> Allow google sheet batch size to be configurable

- src/actions/google/ads/lib/ads_request.ts
- src/actions/slack/legacy_slack/slack.ts
- src/actions/slack/slack.ts
- src/actions/slack/test_utils.ts
- src/actions/slack/utils.ts
This will change the behavior of the Slack form to by default only fetch Channels first, with an option to select users instead. The goal of this change is to reduce the amount of entries initially loaded into the form and stay within Slack API rate limits
> Fetch only users or forms for slack form requests

- src/actions/google/ads/lib/api_client.ts
This is a semi-urgent PR as the Google Ads API v6 is due to sunset on September 8, 2021. After this date, all v6 API requests will begin to fail. This update to use the [v8](https://developers.google.com/google-ads/api/reference/rpc/v8/overview) request path.
FYI @vpoiesz 
See details on the Developer Blog:
https://ads-developers.googleblog.com/2021/07/google-ads-api-v6-sunset-reminder.html
> Google Ads Customer Match - Upgrade API to v8

- src/actions/google/gcs/google_cloud_storage.ts
- src/actions/google/gcs/test_google_cloud_storage.ts
Reorder the filename logic to ensure the extension is always at the end for overwrite = "no"
> Ensure that filetype is preserved for GCS uploads with overwrite false

- src/actions/google/drive/sheets/google_sheets.ts
- src/actions/google/drive/sheets/test_google_sheets.ts
We are not throwing in this method which will cause the action to continue on without finishing as an error.
In addition do not attempt to send more than 5 million cells of data as this will cause upload failures.
> Sheets - do not make batchUpdate calls beyond certain errors and limits

- src/actions/slack/legacy_slack/README.md
Added [chat:write](https://api.slack.com/scopes/chat:write) scope.
> add `chat:write` scope to oauth scope reqs

- src/hub/sources.ts
This would help to search directly by `No action found` string for any particular action
> Update `No action found` error message to contain action name.

- src/actions/google/ads/lib/ads_form_builder.ts
- src/actions/google/ads/lib/api_client.ts
Migrating google ads API from v9  to v11 [[timetable](https://developers.google.com/google-ads/api/docs/sunset-dates)] and using `searchStream` methods in place of GET requests.
> feat: update google ads api to v11

- src/actions/facebook/README.md
- src/actions/facebook/facebook_custom_audiences.ts
- src/actions/facebook/lib/api.ts
- src/actions/facebook/lib/executor.ts
- src/actions/facebook/lib/form_builder.ts
Remove business account form field in place of request for all ad accounts. Also paginate results for ad accounts and custom audiences
> fix: get all ad accounts and paginate for FB

- src/actions/google/drive/sheets/google_sheets.ts
- src/actions/google/drive/sheets/test_google_sheets.ts
Will enable filenames such as `Somebody'sFIle.csv` to be safely passed into a query param for the Drive API
> Sanitize apostrophe's to Google Sheets overwrite

- src/actions/google/ads/lib/api_client.ts
Migrating google ads API from v11 to v12. API v11 will be sunset sometime in March/April 2023 [[see timetable](https://developers.google.com/google-ads/api/docs/sunset-dates#timetable)]
> Update google ads api to v12

- src/actions/facebook/lib/api.ts
Graph API v14 is deprecated April 25th. Upgrading to v15 and v16 does not impact any of the endpoints that we use in this action.
> Update to Facebook Graph API v16

- lib/actions/facebook/lib/api.d.ts
- lib/actions/facebook/lib/api.js
- lib/actions/slack/utils.js
- src/actions/slack/utils.ts
Added new postMessage call for file upload V2 for Slack as it does not support markdown formatted messages
Facebook lib/ update is due to error in previous PR which did not update the lib/ directory
> Add slack postMessage for new upload path

- src/hub/action_request.ts
Promise.all() should be captured and logged to ensure we do not miss an occasion where an error is not properly returned to the Looker instance
> We should capture all errors and log it to be able to debug error instances

- lib/actions/slack/legacy_slack/slack.d.ts
- lib/actions/slack/legacy_slack/slack.js
- lib/actions/slack/slack.d.ts
- lib/actions/slack/slack.js
- src/actions/slack/legacy_slack/slack.ts
- src/actions/slack/slack.ts
- src/actions/slack/test_slack.ts
Slack platform_errors can currently crash a Node process. This PR moves the action to execute in its own process, and further configuration can isolate the action to a queue that will not affect other actions .
> Isolate Slack to its own process to prevent errors from spreading to other actions

- src/actions/slack/test_utils.ts
- src/actions/slack/utils.ts
Add a check for the 'W' prefix. All user uploads must use the older upload path
> User tokens can start with a 'W' as well as a 'U'

- lib/actions/slack/legacy_slack/slack.js
- lib/actions/slack/slack.js
- lib/actions/slack/utils.js
- package.json
- src/actions/slack/legacy_slack/slack.ts
- src/actions/slack/slack.ts
- src/actions/slack/test_utils.ts
- src/actions/slack/utils.ts
Instead of loading channels or users by default, allow the user to manually set the user or channel id. This will allow large orgs the ability to manually set schedules without dealing with rate limiting issues with hitting the conversations.list() api
> Add default ability to manually set target channel or user for Slack action

- src/actions/google/ads/lib/api_client.ts
Migrating google ads API from v12 to v14.
API v12 will be sunset September 27, 2023 [[see timetable](https://developers.google.com/google-ads/api/docs/sunset-dates#timetable)].
API v14 will work until May 2024.
> Update google ads api to v14

- cloudbuild_container.yaml
Using `gcloud builds submit --config="cloudbuild-container.yaml"` - build and deploy an action hub to a GCP project. Env vars still need to be set however
> Update CloudBuild run and deploy for GCP

- lib/actions/airtable/airtable.d.ts
- lib/actions/airtable/airtable.js
- package.json
- src/actions/airtable/airtable.ts
- src/actions/airtable/test_airtable.ts
- src/server/server.ts
- yarn.lock
Adds Airatable OAuth. Since the library provided by Airtable does not provide any wrappers around OAuth, we have opted to implement it on its own. Breaking with original API_KEYS sunset on Jan 31 2024
> Airtable OAuth2

- package.json
This version bump includes the change from Airtable API Key to Airtable OAuth flow.
> Bump actions version to 1.4.1

- lib/actions/airtable/airtable.d.ts
- lib/actions/airtable/airtable.js
- lib/actions/google/drive/google_drive.js
- lib/actions/google/drive/sheets/google_sheets.js
- src/actions/airtable/airtable.ts
- src/actions/airtable/test_airtable.ts
unlike other oauth flows, Airtable uses a chained refresh_token which is reset on every /oauth2/v1/token request. Ensure state is reset in Looker to enable long lived schedules without constant manual reconsent
> Update Airtable Flow to reset state on every request

- lib/actions/sendgrid/sendgrid.js
- src/actions/sendgrid/sendgrid.ts
- src/actions/sendgrid/test_sendgrid.ts
Previously we were throwing with an error message but the ActionContainer was not picking up the errors clearly in the logs. This changes that so on error we return the object the container expects with associtated success=false and error message.
> Adds error messages to response object for sendgrid action.

- lib/actions/airtable/airtable.d.ts
- lib/actions/airtable/airtable.js
- lib/actions/google/gcs/google_cloud_storage.js
- src/actions/airtable/airtable.ts
- src/actions/airtable/test_airtable.ts
This change will move airtable token refresh to when the attempt to reach airtable fails instead of on each request.
This aligns with the airtable style and should work better and increase availability.
> Refactor airtable token refresh

- lib/actions/google/drive/google_drive.js
- lib/actions/google/gcs/google_cloud_storage.js
- lib/error_types/http_errors.d.ts
- lib/hub/action_response.d.ts
- lib/hub/action_response.js
- package.json
- src/actions/google/drive/google_drive.ts
- src/actions/google/drive/test_google_drive.ts
- src/error_types/http_errors.ts
- src/hub/action_response.ts
- yarn.lock
This change will update the google_drive action to return additional data when errors occur during execution.  In addition, this change will fix the google-auth-library to 7.14.1 because there is a bug when updating it.
Lastly, this change also added a helper function when creating http errors.  This is a nice creation function.
> Add error info to google drive and fix dependencies

- lib/actions/google/ads/lib/ads_executor.d.ts
- lib/actions/google/ads/lib/ads_executor.js
- lib/actions/google/ads/lib/ads_form_builder.d.ts
- lib/actions/google/ads/lib/ads_form_builder.js
- lib/actions/google/ads/lib/ads_request.d.ts
- lib/actions/google/ads/lib/ads_request.js
- lib/actions/google/ads/lib/api_client.d.ts
- lib/actions/google/ads/lib/api_client.js
- src/actions/google/ads/lib/ads_executor.ts
- src/actions/google/ads/lib/ads_form_builder.ts
- src/actions/google/ads/lib/ads_request.ts
- src/actions/google/ads/lib/api_client.ts
Migrating google ads API from v14 to v15 with new [consent requirments](https://ads-developers.googleblog.com/2023/10/updates-to-customer-match-conversion.html) for the [consent](https://developers.google.com/google-ads/api/reference/rpc/v15/CustomerMatchUserListMetadata#consent) field.
API v14 will be sunset end of May 2024 [[see timetable](https://developers.google.com/google-ads/api/docs/sunset-dates#timetable)].
API v15 will function until September 2024.
> Update google ads api to v15

- lib/actions/airtable/airtable.js
- src/actions/airtable/airtable.ts
This change will stop updating state when token refresh fails so that the state is not update with old and unusable tokens.
> Remove state from the response when token refresh fails

- lib/actions/google/drive/sheets/google_sheets.js
- lib/error_types/utils.js
- src/error_types/utils.ts
Google returns us error messages but does not include the code or status. For us this means we will return the correct error message but it will be defaulted to a 500 Internal which over inflates our metrics. This is the second pass at trying to categorize the messages to the correct status code. 
These magic strings are taken from the pantheon logs where I look to see if there are any 500 internal errors that are miscatagorized.
> adds more messages to googleErrorType converter

- lib/actions/google/drive/google_drive.js
- src/actions/google/drive/google_drive.ts
This adds error reporting for form requests for Google Drive. We are assuming the error will be the same shape as the execute call but in case it is not, we are adding a list of object keys to the error log as well.
> adds increased error logging to drive form request

- lib/actions/google/drive/sheets/google_sheets.js
- src/actions/google/drive/sheets/google_sheets.ts
This default will restore previous behavior of no action taken on the google sheet form instead of sending :undefined
> Default to root for Sheets Overwrite

- lib/actions/google/drive/sheets/google_sheets.js
- src/actions/google/drive/sheets/google_sheets.ts
This will propagate a proper error back to Looker and make it possible to fix for the customer. Solution would be to go through the oauth flow again.
> Logging and messaging case where Sheets has no oauth tokens

- lib/actions/google/drive/sheets/google_sheets.js
- src/actions/google/drive/sheets/google_sheets.ts
Resizing now is dynamic in blocks of 6000 rows. Enabled via pausing the csv-parser transform stream while resizing takes place. If resizing fails then fail the execution
> Add dynamic resizing for sheets

- lib/actions/google/drive/google_drive.js
- src/actions/google/drive/google_drive.ts
Remove ';base64' from mimeType string when sending in xlsx format so that it does not arrive in zip format
> fix: remove ';base64' from mimeType when is xlsx format

- lib/actions/slack/utils.js
- src/actions/slack/test_utils.ts
- src/actions/slack/utils.ts
~This is currently a breaking change requiring `channel:manage`, `im:write`,`mpim:write`, and `groups:write` added to the scope permissions~
Managed to rewrite in a way that requires no scope creep. If you pass a UXXXX token to `chat.postMessage()` you will receive an implicit conversion to direct message token types (DXXXXX). This was not documented by slack documentation.
> Slack migration from v1 upload

- lib/hub/action_request.d.ts
- src/hub/action_request.ts
Looker is moving to using strings instead of numbers for query_ids. Ensure we support this,
> Add string as possibility for query_id

- src/actions/hubspot/hubspot.ts
- src/actions/hubspot/test_hubspot_companies.ts
- src/actions/hubspot/test_hubspot_contacts.ts
As per https://developers.hubspot.com/docs/guides/apps/private-apps/migrate-an-api-key-integration-to-a-private-app, HubSpot expects to work with Private App Access Token's now.
The change in this PR makes the HubSpot actions work with said Private App Access Token instead.
Otherwise Hubspot actions are unchanged.
> [Hubspot] Migrate to use Private App Access Token

- lib/actions/amazon/amazon_ec2.js
- lib/actions/amazon/amazon_s3.d.ts
- lib/actions/amazon/amazon_s3.js
- package.json
- yarn.lock
Seeing an AWS SDK v2 deprecation warning when spinning up action hub. Following the guidance from the warning and AWS docs: `Please migrate your code to use AWS SDK for JavaScript (v3).`
> Updating AWS SDK from v2 to v3

- lib/hub/action_request.js
- src/hub/action_request.ts
This will prevent sending data through the streams before knowing if the response was actually going to give data
> Cork streams before getting a response

- lib/xpc/execute_process.js
- lib/xpc/extended_execute_process.js
- src/xpc/execute_process.ts
- src/xpc/extended_execute_process.ts
There have been customer issues where they are receiving an error 'error on child: {}'. This usually indicates that the error has non-enumerable properties. This change adds a check to see if the error is of type Error. It also adds increased logging to tell us if the error cannot be Stringified.
> Adds checks to ensure error message gets correctly extracted.

- lib/actions/google/gcs/google_cloud_storage.js
- package.json
- src/actions/google/gcs/google_cloud_storage.ts
- yarn.lock
[ ] Package upgrade from v1.5.2 to v7.16
[ ] add _apiEndpoint_ to GCS client creation
[ ] add _useAuthWithCustomEndpoint : true_ to allow auth connection
[ ] add better error messages when uploading file
[ ] add contentType to metadata object in the stream creation
> chore!: @google-cloud/storage package upgrade from v1.5.2 to v7.16
